Create app
Xodoc/Maxim_Myshko_INDIVIDUAL_MENTORSHIP pull request #1
Opened 2022-01-25 17:10 UTC by Xodoc

2022-01-25 20:34 UTC, alesyalis approved these changes

2022-01-26 21:24 UTC, ihhyy approved these changes

2022-01-28 09:13 UTC, denja2 requested changes

2022-01-28 11:11 UTC, Xodoc commented on ConsoleApp/BL/Services/WeatherService.cs
> +            _validator.ValidateIfEntityExist(weather);
done

2022-01-28 11:12 UTC, Xodoc commented on ConsoleApp/BL/Services/WeatherService.cs
> +        private string GetWeaatherDescription(Root weather)
done

2022-01-28 12:11 UTC, Xodoc commented on ConsoleApp/BL/Services/WeatherService.cs
> +            weather.weather[0].description = GetWeaatherDescription(weather);
done

2022-01-28 12:11 UTC, Xodoc commented on ConsoleApp/BL/Services/WeatherService.cs
> +            return weather.weather[0].description;
done

2022-01-28 12:12 UTC, Xodoc commented on ConsoleApp/BL/Services/WeatherService.cs
> +            var weatherNowDTO = new WeatherNowDTO
done

2022-01-28 12:12 UTC, Xodoc commented on ConsoleApp/BL/Validators/WeatherValidator.cs
> +    public class WeatherValidator : Validator<Root>
done

2022-01-28 13:12 UTC, Xodoc commented on ConsoleApp/Shared/Constants/RequestConstants.cs
> +        public const string UNITS = "metric";
done

2022-01-28 13:12 UTC, Xodoc commented on ConsoleApp/DAL/Repositories/WeatherRepository.cs
> +                var weather = await _client.GetStringAsync($"{URL}{cityName}&lang={LANG}&units={UNITS}&appid={_configuration.APIKey}");
done

2022-01-28 17:15 UTC, Xodoc commented on ConsoleApp/ConsoleApp/Program.cs
> +            _configuration.APIKey = ConfigurationManager.AppSettings["apiKey"];
done

2022-01-28 18:25 UTC, Xodoc commented on ConsoleApp/DAL/Repositories/UnitOfWork.cs
> +    public class UnitOfWork : IUnitOfWork
done

2022-01-31 08:53 UTC, merged