Task 11
Xodoc/Maxim_Myshko_INDIVIDUAL_MENTORSHIP pull request #10
Opened 2022-03-17 21:14 UTC by Xodoc

2022-03-18 12:15 UTC, denja2 requested changes

2022-03-18 12:15 UTC, denja2 commented on ConsoleApp/BL/Services/CityService.cs
>                  if (_config.CityNames.Contains(city.CityName) == false)
P2 iterate by cities from config

2022-03-18 12:15 UTC, denja2 commented on ConsoleApp/IntegrationTests/DI.cs
> +            services.AddDbContext<ApplicationDbContext>(options => options.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=mentorshipdb;Trusted_Connection=True;"));
To config

2022-03-18 12:15 UTC, denja2 commented on ConsoleApp/IntegrationTests/Services/WeatherHistoryServiceIntegrationTest.cs
> +            await _context.WeatherHistories.AddAsync(data);
Arrange

2022-03-18 12:15 UTC, denja2 commented on ConsoleApp/IntegrationTests/Services/WeatherHistoryServiceIntegrationTest.cs
> +            var expected = new WeatherHistoryDTO { CityId = 1, Timestamp = DateTime.Parse(from), Temp = -2.14 };
add more cities

2022-03-18 12:15 UTC, denja2 commented on ConsoleApp/Tests/Services/WeatherHistoryServiceTest.cs
> +        [InlineData("Minsk", "16.03.2022", "17.03.2022")]
Test add method

2022-03-18 12:15 UTC, denja2 commented on ConsoleApp/WebAPI/Controllers/WeatherHistoryController.cs
> +            return Ok(await _weatherHistoryService.GetWeatherHistoriesAsync(request.CityName, DateTime.Parse(request.From), DateTime.Parse(request.To)));
Use datetime arguments

2022-03-18 14:49 UTC, Xodoc commented on ConsoleApp/BL/Services/CityService.cs
>                  if (_config.CityNames.Contains(city.CityName) == false)
done

2022-03-18 15:58 UTC, Xodoc commented on ConsoleApp/IntegrationTests/DI.cs
> +            services.AddDbContext<ApplicationDbContext>(options => options.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=mentorshipdb;Trusted_Connection=True;"));
done

2022-03-18 16:43 UTC, Xodoc commented on ConsoleApp/IntegrationTests/Services/WeatherHistoryServiceIntegrationTest.cs
> +            var expected = new WeatherHistoryDTO { CityId = 1, Timestamp = DateTime.Parse(from), Temp = -2.14 };
done

2022-03-18 17:12 UTC, Xodoc commented on ConsoleApp/WebAPI/Controllers/WeatherHistoryController.cs
> +            return Ok(await _weatherHistoryService.GetWeatherHistoriesAsync(request.CityName, DateTime.Parse(request.From), DateTime.Parse(request.To)));
done

2022-03-18 17:34 UTC, Xodoc commented on ConsoleApp/Tests/Services/WeatherHistoryServiceTest.cs
> +        [InlineData("Minsk", "16.03.2022", "17.03.2022")]
done

2022-03-21 08:53 UTC, denja2 requested changes

2022-03-21 08:53 UTC, denja2 commented on ConsoleApp/BL/Services/CityService.cs
> +                if (oldCities.Any(x => x.CityName == name))
P2 first or default

2022-03-21 08:53 UTC, denja2 commented on ConsoleApp/IntegrationTests/Services/WeatherHistoryServiceIntegrationTest.cs
>          public async void GetWeatherHistoryAsync_WhenSendingCorrectData_GettingWeatherHistory(string cityName, string from, string to)
P3 remove inline data

2022-03-21 08:53 UTC, denja2 commented on ConsoleApp/IntegrationTests/Services/WeatherHistoryServiceIntegrationTest.cs
> +        [Theory]
CheckAndCreateCitiesAsync() in unit test

2022-03-21 12:04 UTC, Xodoc commented on ConsoleApp/BL/Services/CityService.cs
> +                if (oldCities.Any(x => x.CityName == name))
done

2022-03-21 15:01 UTC, Xodoc commented on ConsoleApp/IntegrationTests/Services/WeatherHistoryServiceIntegrationTest.cs
>          public async void GetWeatherHistoryAsync_WhenSendingCorrectData_GettingWeatherHistory(string cityName, string from, string to)
done

2022-03-22 08:32 UTC, denja2 requested changes

2022-03-22 08:32 UTC, denja2 commented on ConsoleApp/WebAPI/Controllers/WeatherController.cs
> +        /// <response code="400">If send data is incorrect</response>
Whats about 500?

2022-03-22 08:42 UTC, Xodoc commented on ConsoleApp/WebAPI/Controllers/WeatherController.cs
> +        /// <response code="400">If send data is incorrect</response>
done

2022-03-22 10:11 UTC, Xodoc commented on ConsoleApp/IntegrationTests/Services/WeatherHistoryServiceIntegrationTest.cs
> +            await _context.WeatherHistories.AddAsync(data);
done

2022-03-22 10:12 UTC, merged