Task 12
Xodoc/Maxim_Myshko_INDIVIDUAL_MENTORSHIP pull request #11
Opened 2022-03-22 11:57 UTC by Xodoc

2022-03-23 15:20 UTC, denja2 requested changes
Move Identity to a separate service

2022-03-25 11:38 UTC, denja2 requested changes

2022-03-25 11:38 UTC, denja2 commented on ConsoleApp/WebAPI/Program.cs
> +                .AddNewtonsoftJson(options => options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore);
Is it necessary to add authorization in task 12?

2022-03-25 19:20 UTC, Xodoc commented on ConsoleApp/WebAPI/Program.cs
> +                .AddNewtonsoftJson(options => options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore);
done

2022-03-29 15:48 UTC, denja2 requested changes

2022-03-29 15:48 UTC, denja2 commented on ConsoleApp/AuthenticationServer/Certificates/SigningAudienceCertificate.cs
> +            string privateXmlKey = File.ReadAllText("./Keys/private_key.xml");
P3 var

2022-03-29 15:48 UTC, denja2 commented on ConsoleApp/AuthenticationServer/Controllers/AuthenticationController.cs
> +        private readonly IAuthenticationService _authenticationService;
P2 rename author

2022-03-29 15:48 UTC, denja2 commented on ConsoleApp/AuthenticationServer/appsettings.json
> +    "Key": "0caebfbd5983024fde00e841734c0762",
Remove

2022-03-29 16:17 UTC, Xodoc commented on ConsoleApp/AuthenticationServer/Controllers/AuthenticationController.cs
> +        private readonly IAuthenticationService _authenticationService;
done

2022-03-29 16:31 UTC, merged