Add WeatherService test
Xodoc/Maxim_Myshko_INDIVIDUAL_MENTORSHIP pull request #2
Opened 2022-01-31 16:41 UTC by Xodoc

2022-02-02 06:05 UTC, alesyalis approved these changes

2022-02-04 06:46 UTC, denja2 requested changes

2022-02-04 06:46 UTC, denja2 commented on ConsoleApp/DAL/Repositories/WeatherRepository.cs
> +                if(result.cod == 404)
HttpStatusses enum

2022-02-04 06:46 UTC, denja2 commented on ConsoleApp/Tests/Services/WeatherServiceTest.cs
> +        [Fact]
see theory approach

2022-02-04 06:46 UTC, denja2 commented on ConsoleApp/Tests/Services/WeatherServiceTest.cs
> +        }
check when exception thrown from validator and repository

2022-02-04 06:46 UTC, denja2 commented on ConsoleApp/Tests/Validators/ValidatorTest.cs
> +        public void Validate_IfEntityIsNull_ValidationIsFailed()
unify with the next

2022-02-04 06:46 UTC, denja2 commented on ConsoleApp/Tests/Validators/ValidatorTest.cs
> +        }
add success pass

2022-02-04 07:35 UTC, Xodoc commented on ConsoleApp/DAL/Repositories/WeatherRepository.cs
> +                if(result.cod == 404)
done

2022-02-04 08:01 UTC, Xodoc commented on ConsoleApp/Tests/Services/WeatherServiceTest.cs
> +        [Fact]
done

2022-02-04 08:29 UTC, Xodoc commented on ConsoleApp/Tests/Validators/ValidatorTest.cs
> +        }
done

2022-02-04 12:08 UTC, Xodoc commented on ConsoleApp/Tests/Services/WeatherServiceTest.cs
> +        }
done

2022-02-07 06:28 UTC, ihhyy approved these changes

2022-02-07 07:08 UTC, denja2 commented on ConsoleApp/Tests/Validators/ValidatorTest.cs
> +        [InlineData(" ")]
add case with ""

2022-02-07 14:19 UTC, Xodoc commented on ConsoleApp/Tests/Validators/ValidatorTest.cs
> +        [InlineData(" ")]
done

2022-02-07 14:26 UTC, merged