Implement new feature GetMaxTemperature
Xodoc/Maxim_Myshko_INDIVIDUAL_MENTORSHIP pull request #5
Opened 2022-02-17 17:10 UTC by Xodoc

2022-02-18 10:57 UTC, denja2 requested changes

2022-02-18 10:57 UTC, denja2 commented on ConsoleApp/DAL/Repositories/WeatherRepository.cs
> +                    Monitor.Pulse(locker);
P1 remove this

2022-02-18 10:57 UTC, denja2 commented on ConsoleApp/DAL/Repositories/WeatherRepository.cs
> +                lock (locker)
P1 Check if it necessary

2022-02-18 10:57 UTC, denja2 commented on ConsoleApp/DAL/Repositories/WeatherRepository.cs
> +            Parallel.For(0, amountCities, i =>
P2 foreach

2022-02-18 10:57 UTC, denja2 commented on ConsoleApp/ConsoleApp/Commands/GetMaxTemperatureCommand.cs
> +            Console.Write("Input number of cities: ");
P1 array of cities

2022-02-18 21:44 UTC, Xodoc commented on ConsoleApp/DAL/Repositories/WeatherRepository.cs
> +            var temperatures = new ConcurrentBag<MaxTemperature>();
done

2022-02-18 21:44 UTC, Xodoc commented on ConsoleApp/DAL/Repositories/WeatherRepository.cs
> +                    Monitor.Pulse(locker);
done

2022-02-18 23:20 UTC, Xodoc commented on ConsoleApp/BL/Interfaces/IWeatherService.cs
> +        Task<string> GetMaxTemperatureAsync(List<string> cityNames, bool debugInfo);
done

2022-02-18 23:27 UTC, Xodoc commented on ConsoleApp/DAL/Repositories/WeatherRepository.cs
> +                lock (locker)
done

2022-02-18 23:27 UTC, Xodoc commented on ConsoleApp/DAL/Repositories/WeatherRepository.cs
> +            Parallel.For(0, amountCities, i =>
done

2022-02-21 08:44 UTC, denja2 requested changes

2022-02-21 08:44 UTC, denja2 commented on ConsoleApp/BL/Services/WeatherService.cs
> +                    if (temp.CountFailedRequests > 0)
P3 Is failed

2022-02-21 08:44 UTC, denja2 commented on ConsoleApp/BL/Services/WeatherService.cs
> +            var responseMessage = "";
P3 stringBuilder

2022-02-21 08:44 UTC, denja2 commented on ConsoleApp/BL/Services/WeatherService.cs
> +            responseMessage += $"City with the highest temperature {maxTemp.Temp}°C: {maxTemp.CityName}." +
P3 use interpolation

2022-02-21 08:44 UTC, denja2 commented on ConsoleApp/ConsoleApp/Commands/GetMaxTemperatureCommand.cs
> +            var array = cities.Split(new string[] {" "}, StringSplitOptions.RemoveEmptyEntries);
P2 notices from demo. P3 move splitting to a separate class

2022-02-21 08:44 UTC, denja2 commented on ConsoleApp/BL/Services/WeatherService.cs
> +        public Task<string> GetMaxTemperatureAsync(List<string> cityNames)
P2 IEnumerable

2022-02-21 08:44 UTC, denja2 commented on ConsoleApp/BL/Validators/Validator.cs
> +        public void ValidateCityNames(List<string> cityNames)
P2 Ienumeruble

2022-02-21 08:44 UTC, denja2 commented on ConsoleApp/DAL/Repositories/WeatherRepository.cs
> +            Parallel.ForEach(cityNames, name =>
P2 Async

2022-02-21 08:44 UTC, denja2 commented on ConsoleApp/DAL/Repositories/WeatherRepository.cs
> +                if (_config.IsDebug)
p3 Manage debug

2022-02-21 21:17 UTC, Xodoc commented on ConsoleApp/BL/Services/WeatherService.cs
> +                    if (temp.CountFailedRequests > 0)
done

2022-02-21 21:35 UTC, Xodoc commented on ConsoleApp/BL/Services/WeatherService.cs
> +        public Task<string> GetMaxTemperatureAsync(List<string> cityNames)
done

2022-02-21 21:35 UTC, Xodoc commented on ConsoleApp/BL/Validators/Validator.cs
> +        public void ValidateCityNames(List<string> cityNames)
done

2022-02-21 21:36 UTC, Xodoc commented on ConsoleApp/DAL/Repositories/WeatherRepository.cs
> +            Parallel.ForEach(cityNames, name =>
done

2022-02-21 22:05 UTC, Xodoc commented on ConsoleApp/DAL/Repositories/WeatherRepository.cs
> +                if (_config.IsDebug)
done

2022-02-21 22:37 UTC, Xodoc commented on ConsoleApp/ConsoleApp/Commands/GetMaxTemperatureCommand.cs
> +            var array = cities.Split(new string[] {" "}, StringSplitOptions.RemoveEmptyEntries);
done

2022-02-21 23:13 UTC, Xodoc commented on ConsoleApp/BL/Services/WeatherService.cs
> +            var responseMessage = "";
done

2022-02-22 09:06 UTC, denja2 commented on ConsoleApp/ConsoleApp/Commands/GetMaxTemperatureCommand.cs
> +            var cityNames = new StringSplit(cities).SplitNames();
P2 Inject in constructor; pass parameters 'cities' in method not class; class name StringSplitter

2022-02-22 09:06 UTC, denja2 commented on ConsoleApp/ConsoleApp/Commands/HelperClasses/StringSplit.cs
> +            return _cityNames.Split(new string[] { " ", "," }, StringSplitOptions.RemoveEmptyEntries);
Trim spaces

2022-02-22 09:13 UTC, Xodoc commented on ConsoleApp/ConsoleApp/Commands/GetMaxTemperatureCommand.cs
> +            var cityNames = new StringSplit(cities).SplitNames();
done

2022-02-22 09:33 UTC, Xodoc commented on ConsoleApp/ConsoleApp/Commands/HelperClasses/StringSplit.cs
> +            return _cityNames.Split(new string[] { " ", "," }, StringSplitOptions.RemoveEmptyEntries);
done

2022-02-22 09:48 UTC, Xodoc commented on ConsoleApp/BL/Services/WeatherService.cs
> +            responseMessage += $"City with the highest temperature {maxTemp.Temp}°C: {maxTemp.CityName}." +
done

2022-02-22 09:48 UTC, merged