Task_8
Xodoc/Maxim_Myshko_INDIVIDUAL_MENTORSHIP pull request #7
Opened 2022-02-23 08:47 UTC by Xodoc

2022-02-23 09:25 UTC, denja2 requested changes

2022-02-23 09:25 UTC, denja2 commented on ConsoleApp/Shared/appsettings.json
> +  "SpecifiedTime": 200
p3 bad name

2022-02-23 09:25 UTC, denja2 commented on ConsoleApp/DAL/Repositories/WeatherRepository.cs
> +                    if (stopwatch.ElapsedMilliseconds > _config.SpecifiedTime)
P1 Token cancellation should be called outside the operation

2022-02-23 09:25 UTC, denja2 commented on ConsoleApp/DAL/Repositories/WeatherRepository.cs
>                      weather = await GetWeatherAsync(name);
P1 Get weather should support Cncelation token

2022-02-23 19:33 UTC, Xodoc commented on ConsoleApp/Shared/appsettings.json
> +  "SpecifiedTime": 200
done

2022-02-23 20:44 UTC, Xodoc commented on ConsoleApp/DAL/Repositories/WeatherRepository.cs
> +                    if (stopwatch.ElapsedMilliseconds > _config.SpecifiedTime)
done

2022-02-23 20:45 UTC, Xodoc commented on ConsoleApp/DAL/Repositories/WeatherRepository.cs
>                      weather = await GetWeatherAsync(name);
done

2022-02-28 10:57 UTC, denja2 commented on ConsoleApp/DAL/Repositories/WeatherRepository.cs
> +        public async Task<CurrentWeather> GetWeatherAsync(string cityName, CancellationTokenSource cts)
Use token

2022-02-28 10:57 UTC, denja2 commented on ConsoleApp/DAL/Repositories/WeatherRepository.cs
> +                if (cts.IsCancellationRequested == true)
pass token in all async methods

2022-03-01 13:29 UTC, Xodoc commented on ConsoleApp/DAL/Repositories/WeatherRepository.cs
> +        public async Task<CurrentWeather> GetWeatherAsync(string cityName, CancellationTokenSource cts)
done

2022-03-01 13:30 UTC, Xodoc commented on ConsoleApp/DAL/Repositories/WeatherRepository.cs
> +                if (cts.IsCancellationRequested == true)
done

2022-03-01 13:30 UTC, merged

2022-03-03 09:05 UTC, denja2 commented on ConsoleApp/DAL/Repositories/WeatherRepository.cs
>                  var weather = await responseMessage.Content.ReadAsStringAsync();
token

2022-03-03 09:05 UTC, denja2 commented on ConsoleApp/DAL/Repositories/WeatherRepository.cs
> +                    ct.ThrowIfCancellationRequested();
no need if

2022-03-03 09:05 UTC, denja2 commented on ConsoleApp/DAL/Repositories/WeatherRepository.cs
> +                    if (ct.IsCancellationRequested == true)
no need