Task_10
Xodoc/Maxim_Myshko_INDIVIDUAL_MENTORSHIP pull request #9
Opened 2022-03-04 01:04 UTC by Xodoc

2022-03-05 11:27 UTC, denja2 requested changes

2022-03-05 11:27 UTC, denja2 commented on ConsoleApp/WebAPI/WebAPI.csproj
> +    <Compile Remove="Controllers\WeatherHistoryController.cs" />
?

2022-03-05 11:27 UTC, denja2 commented on ConsoleApp/WebAPI/Program.cs
> +RecurringJob.AddOrUpdate<IWeatherHistoryService>("addweatherhistory", x => x.AddWeatherHistoryAsync(),
Should be a timer for each city

2022-03-05 11:27 UTC, denja2 commented on ConsoleApp/WebAPI/Program.cs
> +var connection = builder.Configuration.GetConnectionString(�onnectionString);
what is this Ñ

2022-03-05 11:27 UTC, denja2 commented on ConsoleApp/DAL/Repositories/WeatherHistoryRepository.cs
> +    public class WeatherHistoryRepository : IWeatherHistoryRepository
use generic repo for base operatins

2022-03-05 11:27 UTC, denja2 commented on ConsoleApp/DAL/Repositories/WeatherHistoryRepository.cs
> +                var weather = await _weatherRepository.GetWeatherAsync(name, ct);
no business logic here

2022-03-05 13:13 UTC, Xodoc commented on ConsoleApp/WebAPI/WebAPI.csproj
> +    <Compile Remove="Controllers\WeatherHistoryController.cs" />
This is to check if it works

2022-03-05 13:14 UTC, Xodoc commented on ConsoleApp/WebAPI/WebAPI.csproj
> +    <Compile Remove="Controllers\WeatherHistoryController.cs" />
deleted

2022-03-05 13:17 UTC, Xodoc commented on ConsoleApp/WebAPI/Program.cs
> +var connection = builder.Configuration.GetConnectionString(�onnectionString);
So that's it... Accidentally wrote a Russian letter)
Done

2022-03-05 13:19 UTC, Xodoc commented on ConsoleApp/DAL/Repositories/WeatherHistoryRepository.cs
> +    public class WeatherHistoryRepository : IWeatherHistoryRepository
In the next task, I made a generalized repository and transferred operations

2022-03-14 20:21 UTC, denja2 requested changes

2022-03-14 20:21 UTC, denja2 commented on ConsoleApp/BL/Services/WeatherService.cs
> +            Log.Information("Method GetWeatherAsync is complited!");
P3 usually input and output of a method is logged

2022-03-14 20:21 UTC, denja2 commented on ConsoleApp/DAL/Interfaces/ICityRepository.cs
> +        Task<List<City>> CheckAndCreateCities(IEnumerable<string> cities);
P3 async

2022-03-14 20:21 UTC, denja2 commented on ConsoleApp/DAL/Repositories/CityRepository.cs
> +                var city = await _context.Cities.AsNoTracking().FirstOrDefaultAsync(x => x.CityName == name);
P2 is it good approach to read data in a cycle?

2022-03-14 20:21 UTC, denja2 commented on ConsoleApp/DAL/Repositories/CityRepository.cs
> +        public async Task<List<City>> CheckAndCreateCities(IEnumerable<string> cityNames)
P1 No business logic in repo

2022-03-14 20:21 UTC, denja2 commented on ConsoleApp/DAL/Repositories/WeatherHistoryRepository.cs
> +        public async Task<List<WeatherHistory>> GetWeatherHistoriesAsync(string cityName, string date)
P2 is this need in this task

2022-03-14 20:21 UTC, denja2 commented on ConsoleApp/DAL/Repositories/WeatherHistoryRepository.cs
> +            using var scope = _scopeFactory.CreateScope();
scope?

2022-03-14 20:21 UTC, denja2 commented on ConsoleApp/WebAPI/Controllers/WeatherHistoryController.cs
> +    [Route("api/[controller]")]
Task 10 ?

2022-03-14 20:21 UTC, denja2 commented on ConsoleApp/WebAPI/Program.cs
> +        public static IHostBuilder CreateHostBuilder(string[] args)
P2 Task 10?

2022-03-14 20:21 UTC, denja2 commented on ConsoleApp/WindowsBackgroundService/WindowsService.cs
> +        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
P3 good names: token or cancelationToken

2022-03-14 20:21 UTC, denja2 commented on ConsoleApp/WindowsBackgroundService/WindowsService.cs
> +                Log.Information($"Request to the city of {_city.CityName} is complited!" +
P2 error ???

2022-03-15 07:53 UTC, Xodoc commented on ConsoleApp/BL/Services/WeatherService.cs
> +            Log.Information("Method GetWeatherAsync is complited!");
done

2022-03-15 07:54 UTC, Xodoc commented on ConsoleApp/DAL/Interfaces/ICityRepository.cs
> +        Task<List<City>> CheckAndCreateCities(IEnumerable<string> cities);
done

2022-03-15 09:07 UTC, Xodoc commented on ConsoleApp/WindowsBackgroundService/WindowsService.cs
> +        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
Its default name that was suggested)

2022-03-15 09:07 UTC, Xodoc commented on ConsoleApp/WindowsBackgroundService/WindowsService.cs
> +        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
done

2022-03-15 09:43 UTC, Xodoc commented on ConsoleApp/WindowsBackgroundService/WindowsService.cs
> +                Log.Information($"Request to the city of {_city.CityName} is complited!" +
done

2022-03-15 17:07 UTC, Xodoc commented on ConsoleApp/DAL/Repositories/CityRepository.cs
> +                var city = await _context.Cities.AsNoTracking().FirstOrDefaultAsync(x => x.CityName == name);
done

2022-03-15 17:07 UTC, Xodoc commented on ConsoleApp/DAL/Repositories/CityRepository.cs
> +        public async Task<List<City>> CheckAndCreateCities(IEnumerable<string> cityNames)
done

2022-03-15 17:21 UTC, Xodoc commented on ConsoleApp/DAL/Repositories/WeatherHistoryRepository.cs
> +        public async Task<List<WeatherHistory>> GetWeatherHistoriesAsync(string cityName, string date)
done

2022-03-15 17:22 UTC, Xodoc commented on ConsoleApp/WebAPI/Controllers/WeatherHistoryController.cs
> +    [Route("api/[controller]")]
done

2022-03-15 17:24 UTC, Xodoc commented on ConsoleApp/WebAPI/Program.cs
> +        public static IHostBuilder CreateHostBuilder(string[] args)
I'll leave it, because. there will be a lot of redoing)

2022-03-16 08:08 UTC, denja2 commented on ConsoleApp/BL/Validators/Validator.cs
> +                if (string.IsNullOrWhiteSpace(name) || name == string.Empty)
P3 duplicate

2022-03-16 08:14 UTC, Xodoc commented on ConsoleApp/BL/Validators/Validator.cs
> +                if (string.IsNullOrWhiteSpace(name) || name == string.Empty)
done

2022-03-16 08:49 UTC, merged